# Generated by Django 3.1.2 on 2020-10-31 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='store', serialize=False, to='auth.user')),
                ('store_name', models.CharField(blank=True, max_length=500)),
                ('store_address', models.CharField(blank=True, max_length=30)),
                ('store_image', models.ImageField(default='', upload_to='store')),
                ('store_memo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='post')),
                ('memo', models.TextField(blank=True)),
                ('local', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('origin_price', models.IntegerField(default=0)),
                ('new_price', models.IntegerField(default=0)),
                ('soldout', models.BooleanField(default=False)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
