# Generated by Django 3.1.2 on 2020-10-26 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_memo',
        ),
    ]
