# Generated by Django 3.1.2 on 2020-10-26 03:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_profile_store_memo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Store',
        ),
    ]
