# Generated by Django 3.1.2 on 2020-10-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201030_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='post/%Y/%m/%d'),
        ),
    ]
