# Generated by Django 3.1.2 on 2020-11-05 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-store_name']},
        ),
    ]
