# Generated by Django 3.1.2 on 2020-10-24 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('local', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('soldout', models.BooleanField(default=False)),
                ('origin_price', models.IntegerField()),
                ('new_price', models.IntegerField(default=0)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
