# Generated by Django 3.1.2 on 2020-10-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='origin_price',
            field=models.IntegerField(default=0),
        ),
    ]
